[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_finance = "GC7VZh7jh34RZpqpHrsQ39g1Umh1XyWXX1sGidR7fp3K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
setup = "rustup update nightly && cargo update -p anchor-lang -p proc-macro2 && avm use 0.31.1 && agave-install init 2.2.6"
